on:
  push:
    branches:
      - main
  workflow_dispatch:

name: Publish extension

jobs:
  publish-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: echo "nvmrc=$(cat .nvmrc)" >> $GITHUB_ENV
        id: nvmrc

      - uses: actions/setup-node@v3
        with:
          node-version: "${{ env.nvmrc }}"
          cache: npm

      - run: npm ci

      - env:
          VSCE_PAT: "${{ secrets.VSCE_PAT }}"
        run: npm run vscode:publish

      - env:
          OVSX_PAT: "${{ secrets.OVSX_PAT }}"
        run: npm run openvsx:publish

      # - name: Setup tmate session
      #   if: ${{ always() }}
      #   timeout-minutes: 30 # Run `sudo shutdown -h now` to terminate the session
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   uses: mxschmitt/action-tmate@v3
